source 'https://rubygems.org'

gem 'rails'
gem 'mysql2'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'

gem 'aws-sdk', '~> 2'

# Used in notifications
gem 'faraday_middleware'
gem 'faraday-digestauth'

# gem 'npb_logging', github: 'etcetc/npb_logging'
gem 'console_candy', github: 'etcetc/console_candy'
gem 'npb_notification', github: 'etcetc/npb_notification'
gem 'enum_handler', github: 'asux/enum_handler'

# push notification servers
gem 'gcm'
gem 'houston'

# phone helpers
gem 'twilio-ruby'
gem 'global_phone'

gem 'pry-rails'
gem 'figaro', github: 'asux/figaro', branch: 'feature/eb-set-command'
gem 'awesome_print'
gem 'slim-rails'

gem 'bootstrap-sass'
gem 'underscore-rails'
gem 'simple_form'
gem 'rollbar'
gem 'settingslogic'
gem 'rack-attack'
gem 'newrelic_rpm'
gem 'kaminari'
gem 'aasm'
gem 'draper'

gem 'cells'
gem 'cells-slim'
gem 'groupdate'
gem 'chartkick'
gem 'puma'
gem 'hashie'
gem 'neatjson'
gem 'phonelib'

gem 'momentjs-rails', '~> 2.9', github: 'derekprior/momentjs-rails'
gem 'datetimepicker-rails', github: 'zpaulovics/datetimepicker-rails', branch: 'master', submodules: true

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'guard-pow', require: false
  gem 'terminal-notifier-guard'
  gem 'quiet_assets'
  gem 'rb-fchange', require: false
  gem 'rb-fsevent', require: false
  gem 'rb-inotify', require: false
  gem 'rails_layout'
  gem 'rsense'
  gem 'bullet'
  gem 'rack-mini-profiler'
end

group :development, :test do
  gem 'pry-rescue'
  gem 'pry-remote'
  gem 'pry-byebug', '= 1.3.3'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :test do
  gem 'database_cleaner'
  gem 'faker'
  gem 'capybara'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'webmock'
  gem 'vcr'
  gem 'timecop'
end
